// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.robot.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc27.robot.RobotMap;
import org.usfirst.frc27.robot.Robot;


public class HarvesterArm extends Subsystem {
	
	private final DoubleSolenoid harvesterArm;

	private boolean deployed = false;

	public HarvesterArm(){
		harvesterArm = RobotMap.arm;
	}
    
    public void initDefaultCommand() {
    }
    
    public void retract(){
    	harvesterArm.set(Value.kReverse);
    	deployed = false;
    }

    public void deploy(){
		deployed = true;
		Robot.flipper.toggle();
    	harvesterArm.set(Value.kForward);
	}
    public void toggle(){
    	if(deployed){
    		retract();
    	} else {
    		deploy();
    	}

    	SmartDashboard.putBoolean("armDeployed", deployed);
	}

	public boolean isDeployed() {
		return deployed;
	}
}